[package]
name = "hooke-spring"
license = "MIT"
description = "A Lightweight Spring Simulation API in Rust"
version = "0.1.0"
edition = "2024"

[features]
default = ["std", "smol_stopwatch"]
std = []
smol_stopwatch = ["std"]
no_std = ["libm"]
libm = ["dep:libm"]

[dependencies]
libm = { version = "0.2", optional = true }