[package]
name = "hooke-spring"
license = "MIT"
description = "A Lightweight Spring Simulation API in Rust, now also available for Godot!"
repository = "https://github.com/StarlightSora/hooke-spring"
keywords = ["math", "spring", "sim", "godot"]
categories = ["game-development", "mathematics", "no-std"]
version = "0.2.1"
edition = "2024"
#publish = false # Suppress publishing during dev build

[features]
default = ["std", "smol_stopwatch"]
godot_bind = ["dep:godot"]
std = []
smol_stopwatch = ["std"]
no_std = ["libm"]
libm = ["dep:libm"]

[dependencies]
libm = { version = "0.2", optional = true }
godot = { version = "0.5", optional = true }
cargo-docs-rs = "1.0.4"

## Uncomment below two lines if building a standalone cdylib build
#[lib]
#crate-type = ["cdylib"]

[package.metadata.docs.rs]
features = ["godot_bind"]