[package]
name = "hooke-spring"
license = "MIT"
description = "A Lightweight Spring Simulation API in Rust"
repository = "https://github.com/StarlightSora/hooke-spring"
keywords = ["math", "spring", "sim"]
categories = ["game-development", "mathematics", "no-std"]
version = "0.1.1"
edition = "2024"

[features]
default = ["std", "smol_stopwatch"]
std = []
smol_stopwatch = ["std"]
no_std = ["libm"]
libm = ["dep:libm"]

[dependencies]
libm = { version = "0.2", optional = true }